name: payme
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  get_it: ^8.0.3
  equatable: ^2.0.7
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.2
  cached_network_image: ^3.4.1
  mask_text_input_formatter: ^2.9.0
  path_provider: ^2.1.5
  open_file: ^3.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
